# column add
ALTER TABLE COOKINGPAYMENT ADD MERCHANT_UID VARCHAR(50);
ALTER TABLE COOKINGPAYMENT ADD MEMBER_ID VARCHAR(30);
ALTER TABLE COOKINGPAYMENT ADD AMOUNT integer;
ALTER TABLE COOKINGPAYMENT ADD BUYER_EMAIL VARCHAR(50);
ALTER TABLE COOKINGPAYMENT ADD BUYER_TEL VARCHAR(30);
ALTER TABLE COOKINGRESERVATION ADD MEMBER_ID VARCHAR(30);
ALTER TABLE COOKINGRESERVATION ADD CLASS_TITLE VARCHAR(50);
ALTER TABLE COOKINGPAYMENT ADD BUYER_NAME VARCHAR(30);
ALTER TABLE COOKINGRESERVATION ADD RESERVATION_CLASS_DATE VARCHAR(30);
# column name change
ALTER TABLE COOKINGPAYMENT CHANGE CLASS_USERNAME CLASS_MEMBER_ID VARCHAR(30);
ALTER TABLE COOKINGRESERVATION CHANGE CLASS_PEOPLE_RECRUITED reservationVisitor MEDIUMINT;
ALTER TABLE COOKINGPAYMENT CHANGE BUYER_NAME MEMBER_ID VARCHAR(30);
ALTER TABLE COOKINGRESERVATION CHANGE reservationVisitor RESERVATIONVISITOR MEDIUMINT;
#column delete
ALTER TABLE COOKINGPAYMENT DROP COLUMN MEMBER_ID;
ALTER TABLE COOKINGPAYMENT DROP COLUMN PAY_DATE;
        SELECT *
        FROM COOKING C 
        JOIN MEMBERS M ON C.CLASS_MEMBER_ID = M.member_id 
        WHERE C.CLASS_NO ='SaA91IpjxQ'; 
#select
select * from cooking;
SELECT * FROM COOKINGPAYMENT;
SELECT * FROM COOKINGRESERVATION;

select * from members;